name: CI

on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
      - main
    tags:
      - "v*"  # например v1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      # Собираем расширения
      - run: npm run build:chrome
      - run: npm run build:firefox
      - run: npm run build:safari
      # Создаем zip-файлы
      - name: Zip Chrome
        run: zip -r dist/chrome/chrome.zip dist/chrome/*
      - name: Zip Firefox
        run: zip -r dist/firefox/firefox.zip dist/firefox/*
      - name: Zip Safari
        run: zip -r dist/safari/safari.zip dist/safari/*
      # Загружаем zip как артефакты
      - uses: actions/upload-artifact@v4
        with:
          name: extension-builds
          path: |
            dist/chrome/chrome.zip
            dist/firefox/firefox.zip
            dist/safari/safari.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: extension-builds
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/chrome/chrome.zip
            dist/firefox/firefox.zip
            dist/safari/safari.zip
        env:
          # PAT с правами repo, сохранённый в Secrets
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
